### ISSUE TITLE
Error on initial Storybook launch

### ISSUE THREAD

**Issue by Keraito** [storybooks/frontpage#16]
I freshly cloned the repository and ran `yarn install` ->  `yarn run storybook` as per the documentation, but was faced with the following errors:

```
ERROR in ./.storybook/addons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/keraito/OS/frontpage/.storybook/addons.js: Cannot find module '/Users/keraito/OS/frontpage/.cache/babelState.json' (While processing: "/Users/keraito/OS/frontpage/node_modules/babel-preset-gatsby/index.js")
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at loadCachedConfig (/Users/keraito/OS/frontpage/node_modules/babel-preset-gatsby/index.js:11:25)
    at preset (/Users/keraito/OS/frontpage/node_modules/babel-preset-gatsby/index.js:20:29)
    at loadDescriptor (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/full.js:108:6)
    at process.nextTick (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/transform.js:28:33)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./.storybook/addons.js ./node_modules/@storybook/core/dist/client/manager/index.js manager[1]

ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/keraito/OS/frontpage/.storybook/config.js: Cannot find module '/Users/keraito/OS/frontpage/.cache/babelState.json' (While processing: "/Users/keraito/OS/frontpage/node_modules/babel-preset-gatsby/index.js")
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at loadCachedConfig (/Users/keraito/OS/frontpage/node_modules/babel-preset-gatsby/index.js:11:25)
    at preset (/Users/keraito/OS/frontpage/node_modules/babel-preset-gatsby/index.js:20:29)
    at loadDescriptor (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/config/full.js:108:6)
    at process.nextTick (/Users/keraito/OS/frontpage/node_modules/@babel/core/lib/transform.js:28:33)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true iframe[2]
```
Starting the gatsby server via `yarn start` works correctly though.

I tried removing `node_modules` and run `yarn install` again, but that didn't fix it. Using `npm install` -> `npm run storybook` succeeds though. After correctly launching via NPM, doing so via Yarn works as well without error even after deleting the `node_modules` and installing the dependencies via Yarn again. There were changes in the `package-lock.json` after using NPM, but I stashed those before trying with yarn again. 

Information:
- yarn v1.12.3
- NPM v6.4.1

**Comment by Keraito** [comment]
I don't think that's really a long term solution with the popularity of yarn and how Storybook uses yarn in almost all of its documentation 🤔 let's start by checking whether this is reproducible for others? (fresh clone > yarn install > yarn run storybook)

**Comment by domyen** [comment]
@dakebl thanks! Just reproduced this solution on a fresh install. I'll update the readme accordingly.
